version: '3'
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9001:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  sonarqube:
    container_name: sonarqube_container
    image: sonarqube:9.0-community
    restart: unless-stopped
    depends_on:
      - sonar_sql_server
    networks:
      - sonar_net
    environment:
      SONAR_JDBC_URL: jdbc:sqlserver://sonar_sql_server:5433/sonar
      SONAR_JDBC_USERNAME: sa
      SONAR_JDBC_PASSWORD: sonar
      SONAR_WEB_JAVAADDITIONALOPTS: -javaagent:./extensions/plugins/sonarqube-community-branch-plugin.jar=web
      SONAR_CE_JAVAADDITIONALOPTS: -javaagent:./extensions/plugins/sonarqube-community-branch-plugin.jar=ce
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data                 
      - ./sonarqube-community-branch-plugin-1.9.0.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar
      - ./sonarqube-community-branch-plugin-1.9.0.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin.jar
    ports:
      - 9000:9000
    # ulimits:
    #   nproc: 65535
    #   nofiles:
    #     soft: 65536
    #     hard: 65536    
  sonar_sql_server:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    container_name: mssql_server
    restart: unless-stopped
    networks:
      - sonar_net
    ports:
      - 5433:1433
    environment:
      - SA_PASSWORD=sonar
      - ACCEPT_EULA=Y
    volumes:
      - sonar_mssql_data:/var/opt/mssql
  # reverse_proxy:
  #   container_name: reverse_proxy
  #   depends_on:
  #     - sonarqube_container
  #   image: nginx
  #   networks:
  #     - sonar_net
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always
  #   volumes:
  #     - ./notice/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./cert/sonarqube.crt:/etc/ssl/certs/sonarqube.crt
  #     - ./cert/sonar/sonarqube.key:/etc/ssl/private/sonarqube.key

volumes:
  sonarqube_conf:
  sonarqube_data:
  portainer_data:
  sonar_mssql_data:
  
networks:
  sonar_net:
  public:
    driver: bridge
